import type { Metadata } from "next";

import "./globals.css";
import { Montserrat, Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/header/Footer";
import Layout from "@/components/Layout";
import Providers from "@/components/header/Providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // হেডিংয়ের জন্য
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"], // বডির জন্য
});

export const metadata: Metadata = {
  title: "Shopify E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inter.variable}`}>
        <Layout>
          <Header />
          {children}
          <Footer />
          <Providers />
        </Layout>
      </body>
    </html>
  );
}
